//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HWSEdit.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Upgrades {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Upgrades() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HWSEdit.Resources.Upgrades", typeof(Upgrades).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string cat_active_uname {
            get {
                return ResourceManager.GetString("cat_active_uname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combo.
        /// </summary>
        internal static string cat_combo_uname {
            get {
                return ResourceManager.GetString("cat_combo_uname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Core.
        /// </summary>
        internal static string cat_core_uname {
            get {
                return ResourceManager.GetString("cat_core_uname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passive.
        /// </summary>
        internal static string cat_passive_uname {
            get {
                return ResourceManager.GetString("cat_passive_uname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Healing.
        /// </summary>
        internal static string combo_heal_uname {
            get {
                return ResourceManager.GetString("combo_heal_uname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continuously shoots a multi-part nova that does damage while a combo is active..
        /// </summary>
        internal static string combo_nova_udesc_1 {
            get {
                return ResourceManager.GetString("combo_nova_udesc_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increases the nova parts and damage..
        /// </summary>
        internal static string combo_nova_udesc_2 {
            get {
                return ResourceManager.GetString("combo_nova_udesc_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nova.
        /// </summary>
        internal static string combo_nova_uname {
            get {
                return ResourceManager.GetString("combo_nova_uname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timer.
        /// </summary>
        internal static string combo_time_uname {
            get {
                return ResourceManager.GetString("combo_time_uname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Killing 10 enemies in quick succession triggers a combo which increases move speed and damage for a short while..
        /// </summary>
        internal static string combo_udesc {
            get {
                return ResourceManager.GetString("combo_udesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combo.
        /// </summary>
        internal static string combo_uname {
            get {
                return ResourceManager.GetString("combo_uname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armor.
        /// </summary>
        internal static string core_armor_uname {
            get {
                return ResourceManager.GetString("core_armor_uname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health Pool.
        /// </summary>
        internal static string core_hp_uname {
            get {
                return ResourceManager.GetString("core_hp_uname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mana Pool.
        /// </summary>
        internal static string core_mana_uname {
            get {
                return ResourceManager.GetString("core_mana_uname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Speed.
        /// </summary>
        internal static string core_speed_uname {
            get {
                return ResourceManager.GetString("core_speed_uname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level 1.
        /// </summary>
        internal static string lvl1 {
            get {
                return ResourceManager.GetString("lvl1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level 2.
        /// </summary>
        internal static string lvl2 {
            get {
                return ResourceManager.GetString("lvl2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level 3.
        /// </summary>
        internal static string lvl3 {
            get {
                return ResourceManager.GetString("lvl3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level 4.
        /// </summary>
        internal static string lvl4 {
            get {
                return ResourceManager.GetString("lvl4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level 5.
        /// </summary>
        internal static string lvl5 {
            get {
                return ResourceManager.GetString("lvl5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bash.
        /// </summary>
        internal static string pal_bash_uname {
            get {
                return ResourceManager.GetString("pal_bash_uname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage.
        /// </summary>
        internal static string pal_chrg_dmg_uname {
            get {
                return ResourceManager.GetString("pal_chrg_dmg_uname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Range.
        /// </summary>
        internal static string pal_chrg_rng_uname {
            get {
                return ResourceManager.GetString("pal_chrg_rng_uname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charge.
        /// </summary>
        internal static string pal_chrg_uname {
            get {
                return ResourceManager.GetString("pal_chrg_uname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Healing.
        /// </summary>
        internal static string pal_heal_uname {
            get {
                return ResourceManager.GetString("pal_heal_uname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shield.
        /// </summary>
        internal static string pal_shield_uname {
            get {
                return ResourceManager.GetString("pal_shield_uname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arc.
        /// </summary>
        internal static string pal_sword_arc_uname {
            get {
                return ResourceManager.GetString("pal_sword_arc_uname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage.
        /// </summary>
        internal static string pal_sword_dmg_uname {
            get {
                return ResourceManager.GetString("pal_sword_dmg_uname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sword.
        /// </summary>
        internal static string pal_sword_uname {
            get {
                return ResourceManager.GetString("pal_sword_uname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage.
        /// </summary>
        internal static string pal_whirl_dmg_uname {
            get {
                return ResourceManager.GetString("pal_whirl_dmg_uname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        internal static string pal_whirl_dur_uname {
            get {
                return ResourceManager.GetString("pal_whirl_dur_uname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Holy Storm.
        /// </summary>
        internal static string pal_whirl_uname {
            get {
                return ResourceManager.GetString("pal_whirl_uname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage.
        /// </summary>
        internal static string pri_area_dmg_uname {
            get {
                return ResourceManager.GetString("pri_area_dmg_uname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        internal static string pri_area_num_uname {
            get {
                return ResourceManager.GetString("pri_area_num_uname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draining Field.
        /// </summary>
        internal static string pri_area_uname {
            get {
                return ResourceManager.GetString("pri_area_uname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mana Drain.
        /// </summary>
        internal static string pri_aura_drain_uname {
            get {
                return ResourceManager.GetString("pri_aura_drain_uname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slow.
        /// </summary>
        internal static string pri_aura_slow_uname {
            get {
                return ResourceManager.GetString("pri_aura_slow_uname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cripple Aura.
        /// </summary>
        internal static string pri_aura_uname {
            get {
                return ResourceManager.GetString("pri_aura_uname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage.
        /// </summary>
        internal static string pri_beam_dmg_uname {
            get {
                return ResourceManager.GetString("pri_beam_dmg_uname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Range.
        /// </summary>
        internal static string pri_beam_rng_uname {
            get {
                return ResourceManager.GetString("pri_beam_rng_uname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Holy Beam.
        /// </summary>
        internal static string pri_beam_uname {
            get {
                return ResourceManager.GetString("pri_beam_uname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health Regeneration.
        /// </summary>
        internal static string pri_hpregen_uname {
            get {
                return ResourceManager.GetString("pri_hpregen_uname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mana Shield.
        /// </summary>
        internal static string pri_mshield_uname {
            get {
                return ResourceManager.GetString("pri_mshield_uname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage.
        /// </summary>
        internal static string pri_smite_dmg_uname {
            get {
                return ResourceManager.GetString("pri_smite_dmg_uname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed Penalty Reduction.
        /// </summary>
        internal static string pri_smite_spe_uname {
            get {
                return ResourceManager.GetString("pri_smite_spe_uname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smite.
        /// </summary>
        internal static string pri_smite_uname {
            get {
                return ResourceManager.GetString("pri_smite_uname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodge.
        /// </summary>
        internal static string rn_dodge_uname {
            get {
                return ResourceManager.GetString("rn_dodge_uname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage.
        /// </summary>
        internal static string rng_bomb_dmg_uname {
            get {
                return ResourceManager.GetString("rng_bomb_dmg_uname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bomb.
        /// </summary>
        internal static string rng_bomb_uname {
            get {
                return ResourceManager.GetString("rng_bomb_uname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage.
        /// </summary>
        internal static string rng_bow_dmg_uname {
            get {
                return ResourceManager.GetString("rng_bow_dmg_uname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Penetration.
        /// </summary>
        internal static string rng_bow_pen_uname {
            get {
                return ResourceManager.GetString("rng_bow_pen_uname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bow.
        /// </summary>
        internal static string rng_bow_uname {
            get {
                return ResourceManager.GetString("rng_bow_uname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marksmanship.
        /// </summary>
        internal static string rng_crit_uname {
            get {
                return ResourceManager.GetString("rng_crit_uname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        internal static string rng_growth_dur_uname {
            get {
                return ResourceManager.GetString("rng_growth_dur_uname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Range.
        /// </summary>
        internal static string rng_growth_rng_uname {
            get {
                return ResourceManager.GetString("rng_growth_rng_uname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overgrowth.
        /// </summary>
        internal static string rng_growth_uname {
            get {
                return ResourceManager.GetString("rng_growth_uname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrows.
        /// </summary>
        internal static string rng_spread_shts_uname {
            get {
                return ResourceManager.GetString("rng_spread_shts_uname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flurry.
        /// </summary>
        internal static string rng_spread_uname {
            get {
                return ResourceManager.GetString("rng_spread_uname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waves.
        /// </summary>
        internal static string rng_spread_wvs_uname {
            get {
                return ResourceManager.GetString("rng_spread_wvs_uname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length.
        /// </summary>
        internal static string thi_chain_rng_uname {
            get {
                return ResourceManager.GetString("thi_chain_rng_uname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stun.
        /// </summary>
        internal static string thi_chain_stn_uname {
            get {
                return ResourceManager.GetString("thi_chain_stn_uname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chain.
        /// </summary>
        internal static string thi_chain_uname {
            get {
                return ResourceManager.GetString("thi_chain_uname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fervor.
        /// </summary>
        internal static string thi_fervor_uname {
            get {
                return ResourceManager.GetString("thi_fervor_uname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage.
        /// </summary>
        internal static string thi_kfan_dmg_uname {
            get {
                return ResourceManager.GetString("thi_kfan_dmg_uname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Knives.
        /// </summary>
        internal static string thi_kfan_projs_uname {
            get {
                return ResourceManager.GetString("thi_kfan_projs_uname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Knife Fan.
        /// </summary>
        internal static string thi_kfan_uname {
            get {
                return ResourceManager.GetString("thi_kfan_uname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed Penalty Reduction.
        /// </summary>
        internal static string thi_knives_aspeed_uname {
            get {
                return ResourceManager.GetString("thi_knives_aspeed_uname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage.
        /// </summary>
        internal static string thi_knives_dmg_uname {
            get {
                return ResourceManager.GetString("thi_knives_dmg_uname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Knives.
        /// </summary>
        internal static string thi_knives_uname {
            get {
                return ResourceManager.GetString("thi_knives_uname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steal.
        /// </summary>
        internal static string thi_mchance_uname {
            get {
                return ResourceManager.GetString("thi_mchance_uname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Range.
        /// </summary>
        internal static string thi_smoke_rng_uname {
            get {
                return ResourceManager.GetString("thi_smoke_rng_uname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smoke Bomb.
        /// </summary>
        internal static string thi_smoke_uname {
            get {
                return ResourceManager.GetString("thi_smoke_uname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage.
        /// </summary>
        internal static string war_dagger_dmg {
            get {
                return ResourceManager.GetString("war_dagger_dmg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dagger.
        /// </summary>
        internal static string war_dmg_uname {
            get {
                return ResourceManager.GetString("war_dmg_uname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blood Sacrifice.
        /// </summary>
        internal static string war_kheal_uname {
            get {
                return ResourceManager.GetString("war_kheal_uname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soul Sacrifice.
        /// </summary>
        internal static string war_kmana_uname {
            get {
                return ResourceManager.GetString("war_kmana_uname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage.
        /// </summary>
        internal static string war_lightning_dmg_uname {
            get {
                return ResourceManager.GetString("war_lightning_dmg_uname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Targets.
        /// </summary>
        internal static string war_lightning_trg_uname {
            get {
                return ResourceManager.GetString("war_lightning_trg_uname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lightning Strike.
        /// </summary>
        internal static string war_lightning_uname {
            get {
                return ResourceManager.GetString("war_lightning_uname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Life Steal Nova.
        /// </summary>
        internal static string war_steal {
            get {
                return ResourceManager.GetString("war_steal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage.
        /// </summary>
        internal static string war_steal_dmg_uname {
            get {
                return ResourceManager.GetString("war_steal_dmg_uname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        internal static string war_steal_dur_uname {
            get {
                return ResourceManager.GetString("war_steal_dur_uname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electrical Storm.
        /// </summary>
        internal static string war_storm {
            get {
                return ResourceManager.GetString("war_storm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage.
        /// </summary>
        internal static string war_storm_dmg_uname {
            get {
                return ResourceManager.GetString("war_storm_dmg_uname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        internal static string war_storm_dur_uname {
            get {
                return ResourceManager.GetString("war_storm_dur_uname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage.
        /// </summary>
        internal static string wiz_combust_dmg_uname {
            get {
                return ResourceManager.GetString("wiz_combust_dmg_uname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        internal static string wiz_combust_dur_uname {
            get {
                return ResourceManager.GetString("wiz_combust_dur_uname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combustion.
        /// </summary>
        internal static string wiz_combust_uname {
            get {
                return ResourceManager.GetString("wiz_combust_uname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage.
        /// </summary>
        internal static string wiz_fireball_dmg_uname {
            get {
                return ResourceManager.GetString("wiz_fireball_dmg_uname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Range.
        /// </summary>
        internal static string wiz_fireball_rng_uname {
            get {
                return ResourceManager.GetString("wiz_fireball_rng_uname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fireball.
        /// </summary>
        internal static string wiz_fireball_uname {
            get {
                return ResourceManager.GetString("wiz_fireball_uname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frost Shield.
        /// </summary>
        internal static string wiz_fshield_uname {
            get {
                return ResourceManager.GetString("wiz_fshield_uname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage.
        /// </summary>
        internal static string wiz_meteor_dmg_uname {
            get {
                return ResourceManager.GetString("wiz_meteor_dmg_uname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meteors.
        /// </summary>
        internal static string wiz_meteor_num_uname {
            get {
                return ResourceManager.GetString("wiz_meteor_num_uname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meteor Strike.
        /// </summary>
        internal static string wiz_meteor_uname {
            get {
                return ResourceManager.GetString("wiz_meteor_uname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shards.
        /// </summary>
        internal static string wiz_nova_num_uname {
            get {
                return ResourceManager.GetString("wiz_nova_num_uname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Range.
        /// </summary>
        internal static string wiz_nova_rng_uname {
            get {
                return ResourceManager.GetString("wiz_nova_rng_uname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frost Nova.
        /// </summary>
        internal static string wiz_nova_uname {
            get {
                return ResourceManager.GetString("wiz_nova_uname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage.
        /// </summary>
        internal static string wiz_spray_dmg_uname {
            get {
                return ResourceManager.GetString("wiz_spray_dmg_uname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fire Breath.
        /// </summary>
        internal static string wiz_spray_uname {
            get {
                return ResourceManager.GetString("wiz_spray_uname", resourceCulture);
            }
        }
    }
}
